FROM cg

ENV CC=clang-9
ENV CXX=clang++-9

WORKDIR /root/resource

RUN wget https://github.com/talent518/md5/archive/refs/heads/master.zip && unzip md5-master.zip && mv md5-master md5

WORKDIR /root/resource/md5

RUN apt-get install -y python3-dev python-dev

RUN bear make -j`nproc`
RUN cp ~/vanguard/benchmark/genastcmd.py .
RUN python3 genastcmd.py
RUN source buildast.sh

WORKDIR /root/output
RUN ~/vanguard/cmake-build-debug/tools/CallGraphGen/cge ~/resource/libxml2/astList.txt
